# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'intel_window_text.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mpl_figs = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_figs.sizePolicy().hasHeightForWidth())
        self.mpl_figs.setSizePolicy(sizePolicy)
        self.mpl_figs.setMinimumSize(QtCore.QSize(350, 0))
        self.mpl_figs.setMaximumSize(QtCore.QSize(16777215, 650))
        self.mpl_figs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mpl_figs.setProperty("showDropIndicator", False)
        self.mpl_figs.setIconSize(QtCore.QSize(64, 64))
        self.mpl_figs.setMovement(QtWidgets.QListView.Static)
        self.mpl_figs.setResizeMode(QtWidgets.QListView.Adjust)
        self.mpl_figs.setGridSize(QtCore.QSize(64, 64))
        self.mpl_figs.setViewMode(QtWidgets.QListView.IconMode)
        self.mpl_figs.setObjectName("mpl_figs")
        self.gridLayout.addWidget(self.mpl_figs, 1, 1, 1, 1)
        self.sjq = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sjq.sizePolicy().hasHeightForWidth())
        self.sjq.setSizePolicy(sizePolicy)
        self.sjq.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sjq.setObjectName("sjq")
        self.sjq_gl = QtWidgets.QGridLayout(self.sjq)
        self.sjq_gl.setObjectName("sjq_gl")
        self.hnp_button = QtWidgets.QRadioButton(self.sjq)
        self.hnp_button.setObjectName("hnp_button")
        self.sjq_gl.addWidget(self.hnp_button, 5, 0, 1, 1)
        self.nwo_button = QtWidgets.QRadioButton(self.sjq)
        self.nwo_button.setObjectName("nwo_button")
        self.sjq_gl.addWidget(self.nwo_button, 0, 0, 1, 1)
        self.nco_button = QtWidgets.QRadioButton(self.sjq)
        self.nco_button.setObjectName("nco_button")
        self.sjq_gl.addWidget(self.nco_button, 1, 0, 1, 1)
        self.sb_button = QtWidgets.QRadioButton(self.sjq)
        self.sb_button.setObjectName("sb_button")
        self.sjq_gl.addWidget(self.sb_button, 9, 0, 1, 1)
        self.normal_button = QtWidgets.QRadioButton(self.sjq)
        self.normal_button.setObjectName("normal_button")
        self.sjq_gl.addWidget(self.normal_button, 2, 0, 1, 1)
        self.refresh_sjq_button = QtWidgets.QPushButton(self.sjq)
        self.refresh_sjq_button.setObjectName("refresh_sjq_button")
        self.sjq_gl.addWidget(self.refresh_sjq_button, 10, 0, 1, 1)
        self.gridLayout.addWidget(self.sjq, 0, 2, 1, 1)
        self.sjr = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sjr.sizePolicy().hasHeightForWidth())
        self.sjr.setSizePolicy(sizePolicy)
        self.sjr.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sjr.setObjectName("sjr")
        self.sjr_gl = QtWidgets.QGridLayout(self.sjr)
        self.sjr_gl.setObjectName("sjr_gl")
        self.disbond_type = QtWidgets.QGroupBox(self.sjr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disbond_type.sizePolicy().hasHeightForWidth())
        self.disbond_type.setSizePolicy(sizePolicy)
        self.disbond_type.setObjectName("disbond_type")
        self.disbond_gl = QtWidgets.QGridLayout(self.disbond_type)
        self.disbond_gl.setObjectName("disbond_gl")
        self.type4_button = QtWidgets.QRadioButton(self.disbond_type)
        self.type4_button.setObjectName("type4_button")
        self.disbond_gl.addWidget(self.type4_button, 5, 0, 1, 1)
        self.reject_button = QtWidgets.QRadioButton(self.disbond_type)
        self.reject_button.setObjectName("reject_button")
        self.disbond_gl.addWidget(self.reject_button, 6, 0, 1, 1)
        self.type1_button = QtWidgets.QRadioButton(self.disbond_type)
        self.type1_button.setObjectName("type1_button")
        self.disbond_gl.addWidget(self.type1_button, 0, 0, 1, 1)
        self.type3_button = QtWidgets.QRadioButton(self.disbond_type)
        self.type3_button.setObjectName("type3_button")
        self.disbond_gl.addWidget(self.type3_button, 4, 0, 1, 1)
        self.type2_button = QtWidgets.QRadioButton(self.disbond_type)
        self.type2_button.setObjectName("type2_button")
        self.disbond_gl.addWidget(self.type2_button, 1, 0, 1, 1)
        self.sjr_gl.addWidget(self.disbond_type, 0, 0, 1, 1)
        self.dye_stain = QtWidgets.QGroupBox(self.sjr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dye_stain.sizePolicy().hasHeightForWidth())
        self.dye_stain.setSizePolicy(sizePolicy)
        self.dye_stain.setObjectName("dye_stain")
        self.dye_gl = QtWidgets.QGridLayout(self.dye_stain)
        self.dye_gl.setObjectName("dye_gl")
        self.type_d_button = QtWidgets.QRadioButton(self.dye_stain)
        self.type_d_button.setObjectName("type_d_button")
        self.dye_gl.addWidget(self.type_d_button, 3, 0, 1, 1)
        self.type_c_button = QtWidgets.QRadioButton(self.dye_stain)
        self.type_c_button.setObjectName("type_c_button")
        self.dye_gl.addWidget(self.type_c_button, 2, 0, 1, 1)
        self.type_b_button = QtWidgets.QRadioButton(self.dye_stain)
        self.type_b_button.setObjectName("type_b_button")
        self.dye_gl.addWidget(self.type_b_button, 1, 0, 1, 1)
        self.type_a_button = QtWidgets.QRadioButton(self.dye_stain)
        self.type_a_button.setObjectName("type_a_button")
        self.dye_gl.addWidget(self.type_a_button, 0, 0, 1, 1)
        self.type_e_button = QtWidgets.QRadioButton(self.dye_stain)
        self.type_e_button.setObjectName("type_e_button")
        self.dye_gl.addWidget(self.type_e_button, 4, 0, 1, 1)
        self.sjr_gl.addWidget(self.dye_stain, 1, 0, 1, 1)
        self.refresh_sjr_button = QtWidgets.QPushButton(self.sjr)
        self.refresh_sjr_button.setObjectName("refresh_sjr_button")
        self.sjr_gl.addWidget(self.refresh_sjr_button, 2, 0, 1, 1)
        self.sjr_image_button = QtWidgets.QPushButton(self.sjr)
        self.sjr_image_button.setObjectName("sjr_image_button")
        self.sjr_gl.addWidget(self.sjr_image_button, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.sjr, 1, 2, 1, 1)
        self.mpl_window = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_window.sizePolicy().hasHeightForWidth())
        self.mpl_window.setSizePolicy(sizePolicy)
        self.mpl_window.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mpl_window.setObjectName("mpl_window")
        self.mpl_vl = QtWidgets.QVBoxLayout(self.mpl_window)
        self.mpl_vl.setContentsMargins(0, 0, 0, 0)
        self.mpl_vl.setObjectName("mpl_vl")
        self.gridLayout.addWidget(self.mpl_window, 0, 0, 2, 1)
        self.board_pin_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.board_pin_groupbox.setMaximumSize(QtCore.QSize(350, 430))
        self.board_pin_groupbox.setTitle("")
        self.board_pin_groupbox.setObjectName("board_pin_groupbox")
        self.board_name_widget = QtWidgets.QWidget(self.board_pin_groupbox)
        self.board_name_widget.setGeometry(QtCore.QRect(10, 10, 331, 61))
        self.board_name_widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.board_name_widget.setObjectName("board_name_widget")
        self.board_display_label = QtWidgets.QLabel(self.board_name_widget)
        self.board_display_label.setGeometry(QtCore.QRect(6, 0, 321, 51))
        self.board_display_label.setMaximumSize(QtCore.QSize(16777215, 80))
        self.board_display_label.setText("")
        self.board_display_label.setObjectName("board_display_label")
        self.pin_widget = QtWidgets.QWidget(self.board_pin_groupbox)
        self.pin_widget.setGeometry(QtCore.QRect(0, 80, 350, 350))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pin_widget.sizePolicy().hasHeightForWidth())
        self.pin_widget.setSizePolicy(sizePolicy)
        self.pin_widget.setMinimumSize(QtCore.QSize(350, 0))
        self.pin_widget.setMaximumSize(QtCore.QSize(350, 350))
        self.pin_widget.setObjectName("pin_widget")
        self.pin_vl = QtWidgets.QVBoxLayout(self.pin_widget)
        self.pin_vl.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.pin_vl.setContentsMargins(9, 0, 0, 0)
        self.pin_vl.setObjectName("pin_vl")
        self.pin_image = QtWidgets.QLabel(self.pin_widget)
        self.pin_image.setText("")
        self.pin_image.setObjectName("pin_image")
        self.pin_vl.addWidget(self.pin_image)
        self.gridLayout.addWidget(self.board_pin_groupbox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sjq.setTitle(_translate("MainWindow", "SJQ"))
        self.hnp_button.setText(_translate("MainWindow", "HnP"))
        self.nwo_button.setText(_translate("MainWindow", "NWO"))
        self.nco_button.setText(_translate("MainWindow", "NCO"))
        self.sb_button.setText(_translate("MainWindow", "Solder Bridging"))
        self.normal_button.setText(_translate("MainWindow", "Normal"))
        self.refresh_sjq_button.setText(_translate("MainWindow", "Refresh"))
        self.sjr.setTitle(_translate("MainWindow", "SJR"))
        self.disbond_type.setTitle(_translate("MainWindow", "Disbond Type"))
        self.type4_button.setText(_translate("MainWindow", "Type 4"))
        self.reject_button.setText(_translate("MainWindow", "Reject"))
        self.type1_button.setText(_translate("MainWindow", "Type 1"))
        self.type3_button.setText(_translate("MainWindow", "Type 3"))
        self.type2_button.setText(_translate("MainWindow", "Type 2"))
        self.dye_stain.setTitle(_translate("MainWindow", "Dye Stain Percentage "))
        self.type_d_button.setText(_translate("MainWindow", "Type D (61 - 80%)"))
        self.type_c_button.setText(_translate("MainWindow", "Type C (41 - 60%)"))
        self.type_b_button.setText(_translate("MainWindow", "Type B (21 - 40%)"))
        self.type_a_button.setText(_translate("MainWindow", "Type A (1 - 20%)"))
        self.type_e_button.setText(_translate("MainWindow", "Type E (81 - 100%)"))
        self.refresh_sjr_button.setText(_translate("MainWindow", "Refresh"))
        self.sjr_image_button.setText(_translate("MainWindow", "SJR Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

